theme: jekyll-theme-cayman
repository_name: Heena Sharma
title: Heena Sharma
emoji: ðŸš€
description:
  A clean, responsive "Coming Soon" webpage template, perfect for announcing
  upcoming projects or products.
show_downloads: true
collections:
  pages:
    output: true # Generates HTML files for each file
    permalink: /:path/ # URL structure for collection items
